apiVersion: v1
kind: Pod
metadata:
  name: mypod
  namespace: jenkins
  labels:
    name: mypod
spec:
  containers:
    - name: mypod
      image: 352708296901.dkr.ecr.eu-central-1.amazonaws.com/alexey_bot_dev:BOT_DEV_2
